
dev_build:
	docker compose build

dev_push:
	docker compose push sim-5.1.0_lab-2.3.2_selkie_build sim-4.5.0_lab-2.1.0_selkie_build

dev_pull:
	docker compose pull

dev_up:
	docker compose up -d

dev_down:
	docker compose down

dev_purge:
	docker compose down --volumes --remove-orphans

dev_stop:
	docker compose stop

dev_start:
	docker compose start


  