
dev_build:
	docker compose build

dev_push:
	docker compose push dev_webrtc_build

dev_pull:
	docker compose pull

dev_up: dev_build
	docker compose up -d

dev_down:
	docker compose down

dev_purge:
	docker compose down --volumes --remove-orphans


  